# Generated by Django 5.2.9 on 2025-12-04 18:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('cpf_cliente', models.CharField(max_length=11, primary_key=True, serialize=False)),
                ('nome_cliente', models.CharField(max_length=200)),
                ('endereco', models.CharField(max_length=100)),
                ('cidade', models.CharField(max_length=200)),
                ('estado', models.CharField(max_length=100)),
                ('bairro', models.CharField(max_length=200)),
                ('cep', models.CharField(max_length=8)),
                ('telefone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=100)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Motorista',
            fields=[
                ('cpf', models.CharField(max_length=11, primary_key=True, serialize=False)),
                ('nome_motorista', models.CharField(max_length=200)),
                ('telefone', models.CharField(max_length=15)),
                ('data_cadastro', models.DateField()),
                ('cnh', models.CharField(choices=[('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E')], default='B', max_length=1)),
                ('status_motorista', models.CharField(choices=[('A', 'Motorista ativo'), ('I', 'Motorista inativo'), ('R', 'Motorista em rota'), ('D', 'Motorista disponível')], default='D', max_length=1)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Rota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_rota', models.CharField(max_length=200)),
                ('descricao', models.CharField(max_length=300)),
                ('data_rota', models.DateField()),
                ('capacidade_total_utilizada', models.IntegerField(default=0)),
                ('km_total_estimado', models.IntegerField()),
                ('tempo_estimado', models.DurationField()),
                ('status_rota', models.CharField(choices=[('P', 'Rota a planejar'), ('A', 'Rota em andamento'), ('C', 'Rota concluída')], default='P', max_length=1)),
                ('clientes', models.ManyToManyField(to='entregas.cliente')),
                ('motorista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entregas.motorista')),
            ],
        ),
        migrations.CreateModel(
            name='Entrega',
            fields=[
                ('codigo_rastreio', models.CharField(max_length=11, primary_key=True, serialize=False)),
                ('data_entrega_real', models.DateField(blank=True, null=True)),
                ('capacidade_necessaria', models.IntegerField()),
                ('endereco_origem', models.CharField(max_length=100)),
                ('observacoes', models.CharField(blank=True, max_length=300, null=True)),
                ('endereco_destino', models.CharField(max_length=100)),
                ('valor_frete', models.DecimalField(decimal_places=2, max_digits=5)),
                ('data_entrega_prevista', models.DateField()),
                ('data_solicitacao', models.DateField()),
                ('status', models.CharField(choices=[('P', 'Pendente'), ('T', 'Em trânsito'), ('E', 'Entregue'), ('C', 'Cancelada'), ('R', 'Remarcada')], default='P', max_length=1)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entregas.cliente')),
                ('rota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entregas.rota')),
            ],
        ),
        migrations.CreateModel(
            name='Veiculo',
            fields=[
                ('placa', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('modelo', models.CharField(max_length=200)),
                ('capacidade_maxima', models.IntegerField()),
                ('km_atual', models.IntegerField()),
                ('tipo', models.CharField(choices=[('1', 'Carro'), ('2', 'Van'), ('3', 'Caminhão')], default='1', max_length=1)),
                ('status_veiculo', models.CharField(choices=[('D', 'Disponível'), ('U', 'Em uso'), ('M', 'Manutenção')], default='D', max_length=1)),
                ('motorista_ativo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entregas.motorista')),
            ],
        ),
        migrations.AddField(
            model_name='rota',
            name='veiculo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entregas.veiculo'),
        ),
    ]
