# Generated by Django 6.0 on 2025-12-16 03:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entregas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrega',
            name='rota',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='entregas.rota'),
        ),
        migrations.AlterField(
            model_name='veiculo',
            name='capacidade_maxima',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='veiculo',
            name='km_atual',
            field=models.PositiveIntegerField(),
        ),
    ]
