# Generated by Django 6.0 on 2025-12-16 05:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entregas', '0002_alter_entrega_rota_alter_veiculo_capacidade_maxima_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrega',
            name='motorista',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='entregas.motorista'),
        ),
    ]
